version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - addressbook-db:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  addressbook-db:
